apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "online-store.fullname" . }}
  labels:
    app: {{ template "online-store.name" . }}
    chart: {{ template "online-store.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "online-store.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "online-store.name" . }}
        release: {{ .Release.Name }}
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
            weight: 1
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          env:
            - name: APP_INSIGHT_ENABLED
              value: {{ .Values.appInsight.enabled | quote }}
            - name: RPS_THRESHOLD
              value: {{ .Values.app.throttle.limit | quote }}
            - name: SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
{{ toYaml .Values.app.resources | indent 12 }}
        {{- if .Values.appInsight.enabled }}
        - name: {{ .Chart.Name }}-lf
          image: "{{ .Values.lf.image.repository }}:{{ .Values.lf.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          env:
          - name: APPINSIGHTS_INSTRUMENTATIONKEY
            valueFrom:
                secretKeyRef:
                  name: {{ template "online-store.fullname" . }}
                  key: instrumentation-key
          ports:
            - name: http
              containerPort: 55678
              protocol: TCP
          resources:
{{ toYaml .Values.lf.resources | indent 12 }}
        {{- end }}
    {{- with .Values.app.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.app.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.app.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
